### ISSUE TITLE
Use of jq_flasher for flashing BL702 through USB.

### ISSUE THREAD

**Issue by risherlock** [Jatsekku/jq_flasher#3]
Hi @Jatsekku I hope this question is relevant in this issue. Can we use this tool to flash BL702 through USB? Thank you.

**Comment by Jatsekku** [comment]
Hi @risherlock, do you mean virtual UART provided by BL702's USB? 
It should be possible - maybe with some minor tweaks.
This tool is unfortunately not ready yet. I'll check USB compatibility during my next coding session ;)

**Comment by risherlock** [comment]
> Hi @risherlock, do you mean virtual UART provided by BL702's USB? It should be possible - maybe with some minor tweaks. This tool is unfortunately not ready yet. I'll check USB compatibility during my next coding session ;)

Hi @Jatsekku! I meant to flashing BL702 using its USB  without GUI of Bouffalo Labs. I am looking for opensource command line option.

**Comment by Jatsekku** [comment]
That's exactly the purpose of this tool. I was already able to flash some of examples.
Bonus: If you are using the ft232 uart<->usb converter you can upload the binary without touching any buttons;
Actually it was the starting point for this project.
But to be honest I still don't know how it will behave with virtual UART provided by BL702 chip (as I said it was made with ft232 support in mind)
